# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Erg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Erg.proto',
  package='EasyErgsocket',
  serialized_pb=_b('\n\tErg.proto\x12\rEasyErgsocket\"\xfb\x01\n\x03\x45rg\x12\r\n\x05\x65rgId\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\'\n\x07\x65rgtype\x18\x03 \x02(\x0e\x32\x16.EasyErgsocket.ErgType\x12-\n\nplayertype\x18\x04 \x02(\x0e\x32\x19.EasyErgsocket.PlayerType\x12\x10\n\x08\x64istance\x18\x05 \x01(\x01\x12\x14\n\x0c\x65xerciseTime\x18\x06 \x01(\x01\x12\x0f\n\x07\x63\x61\x64\x65nce\x18\x07 \x01(\r\x12\x12\n\npaceInSecs\x18\x08 \x01(\r\x12\x10\n\x08\x63\x61lories\x18\t \x01(\r\x12\r\n\x05power\x18\n \x01(\r\x12\x11\n\theartrate\x18\x0b \x01(\r*0\n\x07\x45rgType\x12\x07\n\x03ROW\x10\x00\x12\x08\n\x04\x42IKE\x10\x01\x12\x07\n\x03RUN\x10\x02\x12\t\n\x05OTHER\x10\x03*,\n\nPlayerType\x12\t\n\x05HUMAN\x10\x00\x12\x07\n\x03\x42OT\x10\x01\x12\n\n\x06REPLAY\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERGTYPE = _descriptor.EnumDescriptor(
  name='ErgType',
  full_name='EasyErgsocket.ErgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIKE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=282,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_ERGTYPE)

ErgType = enum_type_wrapper.EnumTypeWrapper(_ERGTYPE)
_PLAYERTYPE = _descriptor.EnumDescriptor(
  name='PlayerType',
  full_name='EasyErgsocket.PlayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HUMAN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLAY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=332,
  serialized_end=376,
)
_sym_db.RegisterEnumDescriptor(_PLAYERTYPE)

PlayerType = enum_type_wrapper.EnumTypeWrapper(_PLAYERTYPE)
ROW = 0
BIKE = 1
RUN = 2
OTHER = 3
HUMAN = 0
BOT = 1
REPLAY = 2



_ERG = _descriptor.Descriptor(
  name='Erg',
  full_name='EasyErgsocket.Erg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ergId', full_name='EasyErgsocket.Erg.ergId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='EasyErgsocket.Erg.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ergtype', full_name='EasyErgsocket.Erg.ergtype', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playertype', full_name='EasyErgsocket.Erg.playertype', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='EasyErgsocket.Erg.distance', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exerciseTime', full_name='EasyErgsocket.Erg.exerciseTime', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cadence', full_name='EasyErgsocket.Erg.cadence', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paceInSecs', full_name='EasyErgsocket.Erg.paceInSecs', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calories', full_name='EasyErgsocket.Erg.calories', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='EasyErgsocket.Erg.power', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartrate', full_name='EasyErgsocket.Erg.heartrate', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=280,
)

_ERG.fields_by_name['ergtype'].enum_type = _ERGTYPE
_ERG.fields_by_name['playertype'].enum_type = _PLAYERTYPE
DESCRIPTOR.message_types_by_name['Erg'] = _ERG
DESCRIPTOR.enum_types_by_name['ErgType'] = _ERGTYPE
DESCRIPTOR.enum_types_by_name['PlayerType'] = _PLAYERTYPE

Erg = _reflection.GeneratedProtocolMessageType('Erg', (_message.Message,), dict(
  DESCRIPTOR = _ERG,
  __module__ = 'Erg_pb2'
  # @@protoc_insertion_point(class_scope:EasyErgsocket.Erg)
  ))
_sym_db.RegisterMessage(Erg)


# @@protoc_insertion_point(module_scope)
